2021-11-13 23:12:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TESTTABLE[*] TEST(ID INT PRIMARY KEY,
   NAME VARCHAR(32),
   GRADE INT) "; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE TestTable TEST(id INT PRIMARY KEY,
   NAME VARCHAR(32),
   grade INT) [42001-199]
2021-11-13 23:12:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(1001, '山田太郎', 1) [42102-199]
2021-11-13 23:12:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(2001, '太田隆', 2) [42102-199]
2021-11-13 23:12:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(3001, '林敦子', 3) [42102-199]
2021-11-13 23:12:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(3003, '市川次郎', 3) [42102-199]
2021-11-13 23:12:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TESTTABLE[*] (ID INT PRIMARY KEY,
   NAME VARCHAR(32),
   GRADE INT) "; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE TestTable (id INT PRIMARY KEY,
   NAME VARCHAR(32),
   grade INT) [42001-199]
2021-11-13 23:12:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(1001, '山田太郎', 1) [42102-199]
2021-11-13 23:12:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(2001, '太田隆', 2) [42102-199]
2021-11-13 23:12:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(3001, '林敦子', 3) [42102-199]
2021-11-13 23:12:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TESTTABLE" not found; SQL statement:
INSERT INTO TestTable(id, name, grade) VALUES(3003, '市川次郎', 3) [42102-199]
2021-11-13 23:13:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TESTTABLE[*](ID INT PRIMARY KEY,
   NAME VARCHAR(32),
   GRADE INT) "; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE TestTable(id INT PRIMARY KEY,
   NAME VARCHAR(32),
   grade INT) [42001-199]
2021-11-13 23:16:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TESTTABLE[*](ID INT PRIMARY KEY, NAME VARCHAR(32), GRADE INT) "; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE TestTable(id INT PRIMARY KEY, NAME VARCHAR(32), grade INT) [42001-199]
2021-11-13 23:16:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TESTTABLE[*] (ID INT PRIMARY KEY, NAME VARCHAR(32), GRADE INT) "; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE TestTable (id INT PRIMARY KEY, NAME VARCHAR(32), grade INT) [42001-199]
2021-11-13 23:17:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TESTTABLE[*](ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(32), GRADE INT) "; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
CREATE TestTable(id INT not null PRIMARY KEY, NAME VARCHAR(32), grade INT) [42001-199]
2021-11-13 23:30:09 database: wrong user or password; user: "SU"
org.h2.message.DbException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:126)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at quina.jdbc.QuinaDataSource._getRawConnection(QuinaDataSource.java:228)
	at quina.jdbc.QuinaDataSource._getQuinaProxyConnection(QuinaDataSource.java:241)
	at quina.jdbc.QuinaDataSource.getConnection(QuinaDataSource.java:192)
	at quina.test.route.TestDBJsonGet.get(TestDBJsonGet.java:21)
	at quina.component.restful.RESTfulGetSync.call(RESTfulGetSync.java:57)
	at quina.component.RegisterComponent.call(RegisterComponent.java:275)
	at quina.http.server.HttpServerUtil.execComponent(HttpServerUtil.java:152)
	at quina.component.ExecuteComponent.execute(ExecuteComponent.java:67)
	at quina.component.ExecuteComponent.execute(ExecuteComponent.java:56)
	at quina.http.server.HttpServerWorkerCallHandler.executeReceive(HttpServerWorkerCallHandler.java:166)
	at quina.http.server.HttpServerWorkerCall.executeCall(HttpServerWorkerCall.java:63)
	at quina.worker.QuinaWorkerCallHandler.executeCall(QuinaWorkerCallHandler.java:80)
	at quina.worker.QuinaWorkerManager$QuinaWorkerThread.executeCall(QuinaWorkerManager.java:461)
	at quina.worker.QuinaWorkerManager$QuinaWorkerThread.executeCall(QuinaWorkerManager.java:268)
	at quina.QuinaServiceThread.run(QuinaServiceThread.java:174)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 27 more
2021-11-13 23:31:20 database: wrong user or password; user: ""
org.h2.message.DbException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:126)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at quina.jdbc.QuinaDataSource._getRawConnection(QuinaDataSource.java:219)
	at quina.jdbc.QuinaDataSource._getQuinaProxyConnection(QuinaDataSource.java:241)
	at quina.jdbc.QuinaDataSource.getConnection(QuinaDataSource.java:192)
	at quina.test.route.TestDBJsonGet.get(TestDBJsonGet.java:21)
	at quina.component.restful.RESTfulGetSync.call(RESTfulGetSync.java:57)
	at quina.component.RegisterComponent.call(RegisterComponent.java:275)
	at quina.http.server.HttpServerUtil.execComponent(HttpServerUtil.java:152)
	at quina.component.ExecuteComponent.execute(ExecuteComponent.java:67)
	at quina.component.ExecuteComponent.execute(ExecuteComponent.java:56)
	at quina.http.server.HttpServerWorkerCallHandler.executeReceive(HttpServerWorkerCallHandler.java:166)
	at quina.http.server.HttpServerWorkerCall.executeCall(HttpServerWorkerCall.java:63)
	at quina.worker.QuinaWorkerCallHandler.executeCall(QuinaWorkerCallHandler.java:80)
	at quina.worker.QuinaWorkerManager$QuinaWorkerThread.executeCall(QuinaWorkerManager.java:461)
	at quina.worker.QuinaWorkerManager$QuinaWorkerThread.executeCall(QuinaWorkerManager.java:268)
	at quina.QuinaServiceThread.run(QuinaServiceThread.java:174)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 27 more
2021-11-14 00:33:51 database: opening /home/maachang/project/quina/test/h2db/testdb
org.h2.message.DbException: (Message 90086 not found) [90086-199]
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:198)
	at org.h2.engine.Database.getTableEngine(Database.java:3172)
	at org.h2.schema.Schema.createTable(Schema.java:706)
	at org.h2.engine.Database.open(Database.java:824)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at quina.jdbc.QuinaDataSource._getRawConnection(QuinaDataSource.java:228)
	at quina.jdbc.QuinaDataSource._getQuinaProxyConnection(QuinaDataSource.java:241)
	at quina.jdbc.QuinaDataSource.getConnection(QuinaDataSource.java:192)
	at quina.test.route.TestDBJsonGet.get(TestDBJsonGet.java:21)
	at quina.component.restful.RESTfulGetSync.call(RESTfulGetSync.java:57)
	at quina.component.RegisterComponent.call(RegisterComponent.java:275)
	at quina.http.server.HttpServerUtil.execComponent(HttpServerUtil.java:152)
	at quina.component.ExecuteComponent.execute(ExecuteComponent.java:67)
	at quina.component.ExecuteComponent.execute(ExecuteComponent.java:56)
	at quina.http.server.HttpServerWorkerCallHandler.executeReceive(HttpServerWorkerCallHandler.java:166)
	at quina.http.server.HttpServerWorkerCall.executeCall(HttpServerWorkerCall.java:63)
	at quina.worker.QuinaWorkerCallHandler.executeCall(QuinaWorkerCallHandler.java:80)
	at quina.worker.QuinaWorkerManager$QuinaWorkerThread.executeCall(QuinaWorkerManager.java:461)
	at quina.worker.QuinaWorkerManager$QuinaWorkerThread.executeCall(QuinaWorkerManager.java:268)
	at quina.QuinaServiceThread.run(QuinaServiceThread.java:174)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: (Message 90086 not found) [90086-199]
	... 32 more
Caused by: java.lang.ClassNotFoundException: org.h2.mvstore.db.MVTableEngine
	at java.lang.Class.forName(DynamicHub.java:1433)
	at java.lang.Class.forName(DynamicHub.java:1408)
	at org.h2.util.JdbcUtils.loadUserClass(JdbcUtils.java:191)
	... 31 more
